# Generated by Django 2.1.7 on 2019-03-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_post_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='device_id',
            field=models.CharField(default='0000', max_length=300),
        ),
    ]
